/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runcross_painyaya_JNIHttpPost */

#ifndef _Included_com_runcross_painyaya_JNIHttpPost
#define _Included_com_runcross_painyaya_JNIHttpPost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runcross_painyaya_JNIHttpPost
 * Method:    post
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_runcross_painyaya_JNIHttpPost_post
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
