/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runcross_ndktest_JNIWriter */

#ifndef _Included_com_runcross_ndktest_JNIWriter
#define _Included_com_runcross_ndktest_JNIWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runcross_ndktest_JNIWriter
 * Method:    write
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_runcross_ndktest_JNIWriter_write
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
